language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=theoldreader)
  - secure: PJE3zXWCJbz9ZJ2zrHX8YssBDWXpT3SX18A6DUmpUbMqEPt6NcTUpOb+xP30WS5QtoQMYGXb9ZnkdAa97vymGbT1EdG/eE4FH8vFfgqaAK+AjW6gWpire9Wb8eR4KUkfbVChQ8NkoXg/C398+9XVlixrTU6eIayC41J3xDWayES1R/jmBnlJcMjxhZNUmKBvLsmooD8sEpGDKeYTLs5hoCxmMO8fK0BsyCPmnCTa/v9k022v4zgp1Jy9gRu8VVLav/3ddeCU5VQuQPI3SFtQyrjZIOJxvLoHk7+xuSgS8Z5vIowGsjpD9zQQBaQQ5Ewzn886c9unZm3df5DmlVaRepdsRU1LNk0GTe9oKXJl2MuVsX/bl4X1eipNbnqXB8u3dZdcs3m2Xi6V0a9qL3GiijK1NzltF2u6hWzncBod1jchFqWonjiEfQKPGxHoqUOJ+B6EDE203/jPtIi0HC1R4pLHM/dU1M44Nf8YoR+6TdLFF1PhybtqkhLUsnoVuOC5oio1pk5tXimugZCSTWNlDqIlCRhMXFokzWBJO1rVCcLH9n15N6KoawqwlOFxXn/LdUdnDON/rORUfbbLxmgGaarrU7vjLTxxC8TyFFvU5gLyYx9nu6AtgZs7jPwOwzarris52GY6SQ2xY/UO2v/RZ9YHtctCq4nY4ObpeQeD5Uk=
  # MATTERMOST_HOOK_URL
  - secure: rPyFzfHvv4nxxNsIgcP7beAX1z2Hq5gg+XydmgS0IazeI/xdic8hGShEJwDqhESWxEA1v6bcYfg2dOQrol2/bewwax65eOzwwoFUXlGpNLH8pt362Kr7QQxaA8KRi02IyumrkjYyKtoDDBkCI+GE0V5b/yHRUc05K/hfwGwK4Eh0b5iRLx5yXQ6jnFzURN1C3zFQId735893dka+Z+KE5pzbSFcsrgNNzWELPaslBvLwU8DXUxvkHZ3kVr8/2XTSFJOFuhOOx13BAfdyb3avA2iAXlnfJKCJUQPM+ZUzQNICSgKWK4f/LnXo0GdTbtQEu80B7LJ8UdZMzvU+UY5voJIpwpg9vDBvTKMiHNVwxA/CL/5iTQF5bhBvkGxxDFquu2X1duc9cCaqZtzTJ+94AKM2i6BW0/w8MBXlEsULDTFGX9aMCxxshT9weCfqbLo8NrZPuMDf/3dv+ZmgXaDijY/Q59xUaPe6wouNWJJ+330+m8CvxyY9336/8bc0LB2a+LCogBOeCXmVNd0FRmQZzQ5x4c+VPE9N2C4YKvRzanpLemFWHSR+HvKOg6a8lnGEMdDWtOQUS8fGgvqMGkFZ50P47865fRut4ZTKV86CbI+YbljUwtqc4/aoIipdB3j/tWccAMhLNXFicg7Ei1TEUcqDQUiZPwtXwWCUSzQ4/iE=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
